#!/bin/bash


# sudo cp rescan-esata /usr/bin/
# sudo crontab -e
# @reboot /usr/bin/rescan-esata


rescan()
{
	`for i in $(ls /sys/class/scsi_host/); do echo "- - -" > /sys/class/scsi_host/$i/scan; done`	
}

chk_root(){
if [ ! $( id -u ) -eq 0 ]; then
    echo "Please enter root's password."
    exec su -c "${0}" # Call this prog as root
    exit ${?}  # sice we're 'execing' above, we wont reach this exit
               # unless something goes wrong.
  fi
  }

  chk_root
  rescan
